### ISSUE TITLE
New Issue -Passengers Age should be in a Number Field Input.

### ISSUE THREAD

**Issue by lechu837** [leigh-grigaliunas/Generation-Aust-Team-Project-Flight-Booking-Form-Pod2-Group3#10]
As per the requirements, the client needed the age field to be a number field.  As currently, we are displaying the passenger's age as per the Date of Birth, we have to change the type of age field from date of Birth to number to meet the requirements.

**Comment by leigh-grigaliunas** [comment]
UNOT ACTION NEEDED. GOING TO STICK WITH DOB
